use serde::{Serialize, Serializer};

#[derive(Clone, Copy, PartialEq, Debug, Default)]
pub enum CountryCode {
    #[default]
    NotSet,

    Afghanistan,
    AlandIslands,
    Albania,
    Algeria,
    AmericanSamoa,
    Andorra,
    Angola,
    Anguilla,
    Antarctica,
    AntiguaAndBarbuda,
    Argentina,
    Armenia,
    Aruba,
    Australia,
    Austria,
    Azerbaijan,

    Bahamas,
    Bahrain,
    Bangladesh,
    Barbados,
    Belarus,
    Belgium,
    Belize,
    Benin,
    Bermuda,
    Bhutan,
    Bolivia,
    Bonaire,
    BosniaAndHerzegovina,
    Botswana,
    BouvetIsland,
    Brazil,
    BritishIndianOceanTerritory,
    BruneiDarussalam,
    Bulgaria,
    BurkinaFaso,
    Burundi,

    CaboVerde,
    Cambodia,
    Cameroon,
    Canada,
    CaymanIslands,
    CentralAfricanRepublic,
    Chad,
    Chile,
    China,
    ChristmasIsland,
    CocosIslands,
    Colombia,
    Comoros,
    CongoDemocraticRepublic,
    Congo,
    CookIslands,
    CostaRica,
    CoteDIvoire,
    Croatia,
    Cuba,
    Curacao,
    Cyprus,
    Czechia,

    Denmark,
    Djibouti,
    Dominica,
    DominicanRepublic,

    Ecuador,
    Egypt,
    ElSalvador,
    EquatorialGuinea,
    Eritrea,
    Estonia,
    Eswatini,
    Ethiopia,

    FalklandIslands,
    FaroeIslands,
    Fiji,
    Finland,
    France,
    FrenchGuiana,
    FrenchPolynesia,
    FrenchSouthernTerritories,

    Gabon,
    Gambia,
    Georgia,
    Germany,
    Ghana,
    Gibraltar,
    Greece,
    Greenland,
    Grenada,
    Guadeloupe,
    Guam,
    Guatemala,
    Guernsey,
    Guinea,
    GuineaBissau,
    Guyana,

    Haiti,
    HeardIslandAndMcDonaldIslands,
    HolySee,
    Honduras,
    HongKong,
    Hungary,

    Iceland,
    India,
    Indonesia,
    Iran,
    Iraq,
    Ireland,
    IsleOfMan,
    Israel,
    Italy,

    Jamaica,
    Japan,
    Jersey,
    Jordan,

    Kazakhstan,
    Kenya,
    Kiribati,
    KoreaDemocraticPeoplesRepublic,
    KoreaRepublic,
    Kuwait,
    Kyrgyzstan,

    LaoPeoplesDemocraticRepublic,
    Latvia,
    Lebanon,
    Lesotho,
    Liberia,
    Libya,
    Liechtenstein,
    Lithuania,
    Luxembourg,

    Macao,
    Madagascar,
    Malawi,
    Malaysia,
    Maldives,
    Mali,
    Malta,
    MarshallIslands,
    Martinique,
    Mauritania,
    Mauritius,
    Mayotte,
    Mexico,
    Micronesia,
    Moldova,
    Monaco,
    Mongolia,
    Montenegro,
    Montserrat,
    Morocco,
    Mozambique,
    Myanmar,

    Namibia,
    Nauru,
    Nepal,
    Netherlands,
    NewCaledonia,
    NewZealand,
    Nicaragua,
    Niger,
    Nigeria,
    Niue,
    NorfolkIsland,
    NorthMacedonia,
    NorthernMarianaIslands,
    Norway,

    Oman,

    Pakistan,
    Palau,
    Palestine,
    Panama,
    PapuaNewGuinea,
    Paraguay,
    Peru,
    Philippines,
    Pitcairn,
    Poland,
    Portugal,
    PuertoRico,

    Qatar,

    Reunion,
    Romania,
    RussianFederation,
    Rwanda,

    SaintBarthelemy,
    SaintHelena,
    SaintKittsAndNevis,
    SaintLucia,
    SaintMartin,
    SaintPierreAndMiquelon,
    SaintVincentAndTheGrenadines,
    Samoa,
    SanMarino,
    SaoTomeAndPrincipe,
    SaudiArabia,
    Senegal,
    Serbia,
    Seychelles,
    SierraLeone,
    Singapore,
    SintMaarten,
    Slovakia,
    Slovenia,
    SolomonIslands,
    Somalia,
    SouthAfrica,
    SouthGeorgiaAndTheSouthSandwichIslands,
    SouthSudan,
    Spain,
    SriLanka,
    Sudan,
    Suriname,
    SvalbardAndJanMayen,
    Sweden,
    Switzerland,
    SyrianArabRepublic,

    Taiwan,
    Tajikistan,
    Tanzania,
    Thailand,
    TimorLeste,
    Togo,
    Tokelau,
    Tonga,
    TrinidadAndTobago,
    Tunisia,
    Turkey, // The english name according to ISO 3166 is Türkiye
    Turkmenistan,
    TurksAndCaicosIslands,
    Tuvalu,

    Uganda,
    Ukraine,
    UnitedArabEmirates,
    UnitedKingdom,
    UnitedStatesMinorOutlyingIslands,
    UnitedStates,
    Uruguay,
    Uzbekistan,

    Vanuatu,
    Venezuela,
    VietNam,
    VirginIslandsBritish,
    VirginIslandsUS,

    WallisAndFutuna,
    WesternSahara,

    Yemen,

    Zambia,
    Zimbabwe,

    Kosovo,
    UnitedKingdomNorthernIreland,
}

impl TryFrom<&str> for CountryCode {
    type Error = String;

    fn try_from(value: &str) -> Result<Self, Self::Error> {
        match value {
            "NotSet" => Ok(CountryCode::NotSet),
            "AF" => Ok(CountryCode::Afghanistan),
            "AX" => Ok(CountryCode::AlandIslands),
            "AL" => Ok(CountryCode::Albania),
            "DZ" => Ok(CountryCode::Algeria),
            "AS" => Ok(CountryCode::AmericanSamoa),
            "AD" => Ok(CountryCode::Andorra),
            "AO" => Ok(CountryCode::Angola),
            "AI" => Ok(CountryCode::Anguilla),
            "AQ" => Ok(CountryCode::Antarctica),
            "AG" => Ok(CountryCode::AntiguaAndBarbuda),
            "AR" => Ok(CountryCode::Argentina),
            "AM" => Ok(CountryCode::Armenia),
            "AW" => Ok(CountryCode::Aruba),
            "AU" => Ok(CountryCode::Australia),
            "AT" => Ok(CountryCode::Austria),
            "AZ" => Ok(CountryCode::Azerbaijan),

            "BS" => Ok(CountryCode::Bahamas),
            "BH" => Ok(CountryCode::Bahrain),
            "BD" => Ok(CountryCode::Bangladesh),
            "BB" => Ok(CountryCode::Barbados),
            "BY" => Ok(CountryCode::Belarus),
            "BE" => Ok(CountryCode::Belgium),
            "BZ" => Ok(CountryCode::Belize),
            "BJ" => Ok(CountryCode::Benin),
            "BM" => Ok(CountryCode::Bermuda),
            "BT" => Ok(CountryCode::Bhutan),
            "BO" => Ok(CountryCode::Bolivia),
            "BQ" => Ok(CountryCode::Bonaire),
            "BA" => Ok(CountryCode::BosniaAndHerzegovina),
            "BW" => Ok(CountryCode::Botswana),
            "BV" => Ok(CountryCode::BouvetIsland),
            "BR" => Ok(CountryCode::Brazil),
            "IO" => Ok(CountryCode::BritishIndianOceanTerritory),
            "BN" => Ok(CountryCode::BruneiDarussalam),
            "BG" => Ok(CountryCode::Bulgaria),
            "BF" => Ok(CountryCode::BurkinaFaso),
            "BI" => Ok(CountryCode::Burundi),

            "CV" => Ok(CountryCode::CaboVerde),
            "KH" => Ok(CountryCode::Cambodia),
            "CM" => Ok(CountryCode::Cameroon),
            "CA" => Ok(CountryCode::Canada),
            "KY" => Ok(CountryCode::CaymanIslands),
            "CF" => Ok(CountryCode::CentralAfricanRepublic),
            "TD" => Ok(CountryCode::Chad),
            "CL" => Ok(CountryCode::Chile),
            "CN" => Ok(CountryCode::China),
            "CX" => Ok(CountryCode::ChristmasIsland),
            "CC" => Ok(CountryCode::CocosIslands),
            "CO" => Ok(CountryCode::Colombia),
            "KM" => Ok(CountryCode::Comoros),
            "CD" => Ok(CountryCode::CongoDemocraticRepublic),
            "CG" => Ok(CountryCode::Congo),
            "CK" => Ok(CountryCode::CookIslands),
            "CR" => Ok(CountryCode::CostaRica),
            "CI" => Ok(CountryCode::CoteDIvoire),
            "HR" => Ok(CountryCode::Croatia),
            "CU" => Ok(CountryCode::Cuba),
            "CW" => Ok(CountryCode::Curacao),
            "CY" => Ok(CountryCode::Cyprus),
            "CZ" => Ok(CountryCode::Czechia),

            "DK" => Ok(CountryCode::Denmark),
            "DJ" => Ok(CountryCode::Djibouti),
            "DM" => Ok(CountryCode::Dominica),
            "DO" => Ok(CountryCode::DominicanRepublic),

            "EC" => Ok(CountryCode::Ecuador),
            "EG" => Ok(CountryCode::Egypt),
            "SV" => Ok(CountryCode::ElSalvador),
            "GQ" => Ok(CountryCode::EquatorialGuinea),
            "ER" => Ok(CountryCode::Eritrea),
            "EE" => Ok(CountryCode::Estonia),
            "SZ" => Ok(CountryCode::Eswatini),
            "ET" => Ok(CountryCode::Ethiopia),

            "FK" => Ok(CountryCode::FalklandIslands),
            "FO" => Ok(CountryCode::FaroeIslands),
            "FJ" => Ok(CountryCode::Fiji),
            "FI" => Ok(CountryCode::Finland),
            "FR" => Ok(CountryCode::France),
            "GF" => Ok(CountryCode::FrenchGuiana),
            "PF" => Ok(CountryCode::FrenchPolynesia),
            "TF" => Ok(CountryCode::FrenchSouthernTerritories),

            "GA" => Ok(CountryCode::Gabon),
            "GM" => Ok(CountryCode::Gambia),
            "GE" => Ok(CountryCode::Georgia),
            "DE" => Ok(CountryCode::Germany),
            "GH" => Ok(CountryCode::Ghana),
            "GI" => Ok(CountryCode::Gibraltar),
            "EL" => Ok(CountryCode::Greece),
            "GL" => Ok(CountryCode::Greenland),
            "GD" => Ok(CountryCode::Grenada),
            "GP" => Ok(CountryCode::Guadeloupe),
            "GU" => Ok(CountryCode::Guam),
            "GT" => Ok(CountryCode::Guatemala),
            "GG" => Ok(CountryCode::Guernsey),
            "GN" => Ok(CountryCode::Guinea),
            "GW" => Ok(CountryCode::GuineaBissau),
            "GY" => Ok(CountryCode::Guyana),

            "HT" => Ok(CountryCode::Haiti),
            "HM" => Ok(CountryCode::HeardIslandAndMcDonaldIslands),
            "VA" => Ok(CountryCode::HolySee),
            "HN" => Ok(CountryCode::Honduras),
            "HK" => Ok(CountryCode::HongKong),
            "HU" => Ok(CountryCode::Hungary),

            "IS" => Ok(CountryCode::Iceland),
            "IN" => Ok(CountryCode::India),
            "ID" => Ok(CountryCode::Indonesia),
            "IR" => Ok(CountryCode::Iran),
            "IQ" => Ok(CountryCode::Iraq),
            "IE" => Ok(CountryCode::Ireland),
            "IM" => Ok(CountryCode::IsleOfMan),
            "IL" => Ok(CountryCode::Israel),
            "IT" => Ok(CountryCode::Italy),

            "JM" => Ok(CountryCode::Jamaica),
            "JP" => Ok(CountryCode::Japan),
            "JE" => Ok(CountryCode::Jersey),
            "JO" => Ok(CountryCode::Jordan),

            "KZ" => Ok(CountryCode::Kazakhstan),
            "KE" => Ok(CountryCode::Kenya),
            "KI" => Ok(CountryCode::Kiribati),
            "KP" => Ok(CountryCode::KoreaDemocraticPeoplesRepublic),
            "KR" => Ok(CountryCode::KoreaRepublic),
            "KW" => Ok(CountryCode::Kuwait),
            "KG" => Ok(CountryCode::Kyrgyzstan),

            "LA" => Ok(CountryCode::LaoPeoplesDemocraticRepublic),
            "LV" => Ok(CountryCode::Latvia),
            "LB" => Ok(CountryCode::Lebanon),
            "LS" => Ok(CountryCode::Lesotho),
            "LR" => Ok(CountryCode::Liberia),
            "LY" => Ok(CountryCode::Libya),
            "LI" => Ok(CountryCode::Liechtenstein),
            "LT" => Ok(CountryCode::Lithuania),
            "LU" => Ok(CountryCode::Luxembourg),

            "MO" => Ok(CountryCode::Macao),
            "MG" => Ok(CountryCode::Madagascar),
            "MW" => Ok(CountryCode::Malawi),
            "MY" => Ok(CountryCode::Malaysia),
            "MV" => Ok(CountryCode::Maldives),
            "ML" => Ok(CountryCode::Mali),
            "MT" => Ok(CountryCode::Malta),
            "MH" => Ok(CountryCode::MarshallIslands),
            "MQ" => Ok(CountryCode::Martinique),
            "MR" => Ok(CountryCode::Mauritania),
            "MU" => Ok(CountryCode::Mauritius),
            "YT" => Ok(CountryCode::Mayotte),
            "MX" => Ok(CountryCode::Mexico),
            "FM" => Ok(CountryCode::Micronesia),
            "MD" => Ok(CountryCode::Moldova),
            "MC" => Ok(CountryCode::Monaco),
            "MN" => Ok(CountryCode::Mongolia),
            "ME" => Ok(CountryCode::Montenegro),
            "MS" => Ok(CountryCode::Montserrat),
            "MA" => Ok(CountryCode::Morocco),
            "MZ" => Ok(CountryCode::Mozambique),
            "MM" => Ok(CountryCode::Myanmar),

            "NA" => Ok(CountryCode::Namibia),
            "NR" => Ok(CountryCode::Nauru),
            "NP" => Ok(CountryCode::Nepal),
            "NL" => Ok(CountryCode::Netherlands),
            "NC" => Ok(CountryCode::NewCaledonia),
            "NZ" => Ok(CountryCode::NewZealand),
            "NI" => Ok(CountryCode::Nicaragua),
            "NE" => Ok(CountryCode::Niger),
            "NG" => Ok(CountryCode::Nigeria),
            "NU" => Ok(CountryCode::Niue),
            "NF" => Ok(CountryCode::NorfolkIsland),
            "c" => Ok(CountryCode::NorthMacedonia),
            "MP" => Ok(CountryCode::NorthernMarianaIslands),
            "NO" => Ok(CountryCode::Norway),

            "OM" => Ok(CountryCode::Oman),

            "PK" => Ok(CountryCode::Pakistan),
            "PW" => Ok(CountryCode::Palau),
            "PS" => Ok(CountryCode::Palestine),
            "PA" => Ok(CountryCode::Panama),
            "PG" => Ok(CountryCode::PapuaNewGuinea),
            "PY" => Ok(CountryCode::Paraguay),
            "PE" => Ok(CountryCode::Peru),
            "PH" => Ok(CountryCode::Philippines),
            "PN" => Ok(CountryCode::Pitcairn),
            "PL" => Ok(CountryCode::Poland),
            "PT" => Ok(CountryCode::Portugal),
            "PR" => Ok(CountryCode::PuertoRico),

            "QA" => Ok(CountryCode::Qatar),

            "RE" => Ok(CountryCode::Reunion),
            "RO" => Ok(CountryCode::Romania),
            "RU" => Ok(CountryCode::RussianFederation),
            "RW" => Ok(CountryCode::Rwanda),

            "BL" => Ok(CountryCode::SaintBarthelemy),
            "SH" => Ok(CountryCode::SaintHelena),
            "KN" => Ok(CountryCode::SaintKittsAndNevis),
            "LC" => Ok(CountryCode::SaintLucia),
            "MF" => Ok(CountryCode::SaintMartin),
            "PM" => Ok(CountryCode::SaintPierreAndMiquelon),
            "VC" => Ok(CountryCode::SaintVincentAndTheGrenadines),
            "WS" => Ok(CountryCode::Samoa),
            "SM" => Ok(CountryCode::SanMarino),
            "ST" => Ok(CountryCode::SaoTomeAndPrincipe),
            "SA" => Ok(CountryCode::SaudiArabia),
            "SN" => Ok(CountryCode::Senegal),
            "RS" => Ok(CountryCode::Serbia),
            "SC" => Ok(CountryCode::Seychelles),
            "SL" => Ok(CountryCode::SierraLeone),
            "SG" => Ok(CountryCode::Singapore),
            "SX" => Ok(CountryCode::SintMaarten),
            "SK" => Ok(CountryCode::Slovakia),
            "SI" => Ok(CountryCode::Slovenia),
            "SB" => Ok(CountryCode::SolomonIslands),
            "SO" => Ok(CountryCode::Somalia),
            "ZA" => Ok(CountryCode::SouthAfrica),
            "GS" => Ok(CountryCode::SouthGeorgiaAndTheSouthSandwichIslands),
            "SS" => Ok(CountryCode::SouthSudan),
            "ES" => Ok(CountryCode::Spain),
            "LK" => Ok(CountryCode::SriLanka),
            "SD" => Ok(CountryCode::Sudan),
            "SR" => Ok(CountryCode::Suriname),
            "SJ" => Ok(CountryCode::SvalbardAndJanMayen),
            "SE" => Ok(CountryCode::Sweden),
            "CH" => Ok(CountryCode::Switzerland),
            "SY" => Ok(CountryCode::SyrianArabRepublic),

            "TW" => Ok(CountryCode::Taiwan),
            "TJ" => Ok(CountryCode::Tajikistan),
            "TZ" => Ok(CountryCode::Tanzania),
            "TH" => Ok(CountryCode::Thailand),
            "TL" => Ok(CountryCode::TimorLeste),
            "TG" => Ok(CountryCode::Togo),
            "TK" => Ok(CountryCode::Tokelau),
            "TO" => Ok(CountryCode::Tonga),
            "TT" => Ok(CountryCode::TrinidadAndTobago),
            "TN" => Ok(CountryCode::Tunisia),
            "TR" => Ok(CountryCode::Turkey),
            "TM" => Ok(CountryCode::Turkmenistan),
            "TC" => Ok(CountryCode::TurksAndCaicosIslands),
            "TV" => Ok(CountryCode::Tuvalu),

            "UG" => Ok(CountryCode::Uganda),
            "UA" => Ok(CountryCode::Ukraine),
            "AE" => Ok(CountryCode::UnitedArabEmirates),
            "GB" => Ok(CountryCode::UnitedKingdom),
            "UM" => Ok(CountryCode::UnitedStatesMinorOutlyingIslands),
            "US" => Ok(CountryCode::UnitedStates),
            "UY" => Ok(CountryCode::Uruguay),
            "UZ" => Ok(CountryCode::Uzbekistan),

            "VU" => Ok(CountryCode::Vanuatu),
            "VE" => Ok(CountryCode::Venezuela),
            "VN" => Ok(CountryCode::VietNam),
            "VG" => Ok(CountryCode::VirginIslandsBritish),
            "VI" => Ok(CountryCode::VirginIslandsUS),

            "WF" => Ok(CountryCode::WallisAndFutuna),
            "EH" => Ok(CountryCode::WesternSahara),

            "YE" => Ok(CountryCode::Yemen),

            "ZM" => Ok(CountryCode::Zambia),
            "ZW" => Ok(CountryCode::Zimbabwe),

            "1A" => Ok(CountryCode::Kosovo),
            "XI" => Ok(CountryCode::UnitedKingdomNorthernIreland),

            _ => Err("Country code not detected".into()),
        }
    }
}

impl CountryCode {
    pub fn as_str(&self) -> &str {
        match self {
            CountryCode::NotSet => "NotSet",
            CountryCode::Afghanistan => "AF",
            CountryCode::AlandIslands => "AX",
            CountryCode::Albania => "AL",
            CountryCode::Algeria => "DZ",
            CountryCode::AmericanSamoa => "AS",
            CountryCode::Andorra => "AD",
            CountryCode::Angola => "AO",
            CountryCode::Anguilla => "AI",
            CountryCode::Antarctica => "AQ",
            CountryCode::AntiguaAndBarbuda => "AG",
            CountryCode::Argentina => "AR",
            CountryCode::Armenia => "AM",
            CountryCode::Aruba => "AW",
            CountryCode::Australia => "AU",
            CountryCode::Austria => "AT",
            CountryCode::Azerbaijan => "AZ",

            CountryCode::Bahamas => "BS",
            CountryCode::Bahrain => "BH",
            CountryCode::Bangladesh => "BD",
            CountryCode::Barbados => "BB",
            CountryCode::Belarus => "BY",
            CountryCode::Belgium => "BE",
            CountryCode::Belize => "BZ",
            CountryCode::Benin => "BJ",
            CountryCode::Bermuda => "BM",
            CountryCode::Bhutan => "BT",
            CountryCode::Bolivia => "BO",
            CountryCode::Bonaire => "BQ",
            CountryCode::BosniaAndHerzegovina => "BA",
            CountryCode::Botswana => "BW",
            CountryCode::BouvetIsland => "BV",
            CountryCode::Brazil => "BR",
            CountryCode::BritishIndianOceanTerritory => "IO",
            CountryCode::BruneiDarussalam => "BN",
            CountryCode::Bulgaria => "BG",
            CountryCode::BurkinaFaso => "BF",
            CountryCode::Burundi => "BI",

            CountryCode::CaboVerde => "CV",
            CountryCode::Cambodia => "KH",
            CountryCode::Cameroon => "CM",
            CountryCode::Canada => "CA",
            CountryCode::CaymanIslands => "KY",
            CountryCode::CentralAfricanRepublic => "CF",
            CountryCode::Chad => "TD",
            CountryCode::Chile => "CL",
            CountryCode::China => "CN",
            CountryCode::ChristmasIsland => "CX",
            CountryCode::CocosIslands => "CC",
            CountryCode::Colombia => "CO",
            CountryCode::Comoros => "KM",
            CountryCode::CongoDemocraticRepublic => "CD",
            CountryCode::Congo => "CG",
            CountryCode::CookIslands => "CK",
            CountryCode::CostaRica => "CR",
            CountryCode::CoteDIvoire => "CI",
            CountryCode::Croatia => "HR",
            CountryCode::Cuba => "CU",
            CountryCode::Curacao => "CW",
            CountryCode::Cyprus => "CY",
            CountryCode::Czechia => "CZ",

            CountryCode::Denmark => "DK",
            CountryCode::Djibouti => "DJ",
            CountryCode::Dominica => "DM",
            CountryCode::DominicanRepublic => "DO",

            CountryCode::Ecuador => "EC",
            CountryCode::Egypt => "EG",
            CountryCode::ElSalvador => "SV",
            CountryCode::EquatorialGuinea => "GQ",
            CountryCode::Eritrea => "ER",
            CountryCode::Estonia => "EE",
            CountryCode::Eswatini => "SZ",
            CountryCode::Ethiopia => "ET",

            CountryCode::FalklandIslands => "FK",
            CountryCode::FaroeIslands => "FO",
            CountryCode::Fiji => "FJ",
            CountryCode::Finland => "FI",
            CountryCode::France => "FR",
            CountryCode::FrenchGuiana => "GF",
            CountryCode::FrenchPolynesia => "PF",
            CountryCode::FrenchSouthernTerritories => "TF",

            CountryCode::Gabon => "GA",
            CountryCode::Gambia => "GM",
            CountryCode::Georgia => "GE",
            CountryCode::Germany => "DE",
            CountryCode::Ghana => "GH",
            CountryCode::Gibraltar => "GI",
            CountryCode::Greece => "EL",
            CountryCode::Greenland => "GL",
            CountryCode::Grenada => "GD",
            CountryCode::Guadeloupe => "GP",
            CountryCode::Guam => "GU",
            CountryCode::Guatemala => "GT",
            CountryCode::Guernsey => "GG",
            CountryCode::Guinea => "GN",
            CountryCode::GuineaBissau => "GW",
            CountryCode::Guyana => "GY",

            CountryCode::Haiti => "HT",
            CountryCode::HeardIslandAndMcDonaldIslands => "HM",
            CountryCode::HolySee => "VA",
            CountryCode::Honduras => "HN",
            CountryCode::HongKong => "HK",
            CountryCode::Hungary => "HU",

            CountryCode::Iceland => "IS",
            CountryCode::India => "IN",
            CountryCode::Indonesia => "ID",
            CountryCode::Iran => "IR",
            CountryCode::Iraq => "IQ",
            CountryCode::Ireland => "IE",
            CountryCode::IsleOfMan => "IM",
            CountryCode::Israel => "IL",
            CountryCode::Italy => "IT",

            CountryCode::Jamaica => "JM",
            CountryCode::Japan => "JP",
            CountryCode::Jersey => "JE",
            CountryCode::Jordan => "JO",

            CountryCode::Kazakhstan => "KZ",
            CountryCode::Kenya => "KE",
            CountryCode::Kiribati => "KI",
            CountryCode::KoreaDemocraticPeoplesRepublic => "KP",
            CountryCode::KoreaRepublic => "KR",
            CountryCode::Kuwait => "KW",
            CountryCode::Kyrgyzstan => "KG",

            CountryCode::LaoPeoplesDemocraticRepublic => "LA",
            CountryCode::Latvia => "LV",
            CountryCode::Lebanon => "LB",
            CountryCode::Lesotho => "LS",
            CountryCode::Liberia => "LR",
            CountryCode::Libya => "LY",
            CountryCode::Liechtenstein => "LI",
            CountryCode::Lithuania => "LT",
            CountryCode::Luxembourg => "LU",

            CountryCode::Macao => "MO",
            CountryCode::Madagascar => "MG",
            CountryCode::Malawi => "MW",
            CountryCode::Malaysia => "MY",
            CountryCode::Maldives => "MV",
            CountryCode::Mali => "ML",
            CountryCode::Malta => "MT",
            CountryCode::MarshallIslands => "MH",
            CountryCode::Martinique => "MQ",
            CountryCode::Mauritania => "MR",
            CountryCode::Mauritius => "MU",
            CountryCode::Mayotte => "YT",
            CountryCode::Mexico => "MX",
            CountryCode::Micronesia => "FM",
            CountryCode::Moldova => "MD",
            CountryCode::Monaco => "MC",
            CountryCode::Mongolia => "MN",
            CountryCode::Montenegro => "ME",
            CountryCode::Montserrat => "MS",
            CountryCode::Morocco => "MA",
            CountryCode::Mozambique => "MZ",
            CountryCode::Myanmar => "MM",

            CountryCode::Namibia => "NA",
            CountryCode::Nauru => "NR",
            CountryCode::Nepal => "NP",
            CountryCode::Netherlands => "NL",
            CountryCode::NewCaledonia => "NC",
            CountryCode::NewZealand => "NZ",
            CountryCode::Nicaragua => "NI",
            CountryCode::Niger => "NE",
            CountryCode::Nigeria => "NG",
            CountryCode::Niue => "NU",
            CountryCode::NorfolkIsland => "NF",
            CountryCode::NorthMacedonia => "c",
            CountryCode::NorthernMarianaIslands => "MP",
            CountryCode::Norway => "NO",

            CountryCode::Oman => "OM",

            CountryCode::Pakistan => "PK",
            CountryCode::Palau => "PW",
            CountryCode::Palestine => "PS",
            CountryCode::Panama => "PA",
            CountryCode::PapuaNewGuinea => "PG",
            CountryCode::Paraguay => "PY",
            CountryCode::Peru => "PE",
            CountryCode::Philippines => "PH",
            CountryCode::Pitcairn => "PN",
            CountryCode::Poland => "PL",
            CountryCode::Portugal => "PT",
            CountryCode::PuertoRico => "PR",

            CountryCode::Qatar => "QA",

            CountryCode::Reunion => "RE",
            CountryCode::Romania => "RO",
            CountryCode::RussianFederation => "RU",
            CountryCode::Rwanda => "RW",

            CountryCode::SaintBarthelemy => "BL",
            CountryCode::SaintHelena => "SH",
            CountryCode::SaintKittsAndNevis => "KN",
            CountryCode::SaintLucia => "LC",
            CountryCode::SaintMartin => "MF",
            CountryCode::SaintPierreAndMiquelon => "PM",
            CountryCode::SaintVincentAndTheGrenadines => "VC",
            CountryCode::Samoa => "WS",
            CountryCode::SanMarino => "SM",
            CountryCode::SaoTomeAndPrincipe => "ST",
            CountryCode::SaudiArabia => "SA",
            CountryCode::Senegal => "SN",
            CountryCode::Serbia => "RS",
            CountryCode::Seychelles => "SC",
            CountryCode::SierraLeone => "SL",
            CountryCode::Singapore => "SG",
            CountryCode::SintMaarten => "SX",
            CountryCode::Slovakia => "SK",
            CountryCode::Slovenia => "SI",
            CountryCode::SolomonIslands => "SB",
            CountryCode::Somalia => "SO",
            CountryCode::SouthAfrica => "ZA",
            CountryCode::SouthGeorgiaAndTheSouthSandwichIslands => "GS",
            CountryCode::SouthSudan => "SS",
            CountryCode::Spain => "ES",
            CountryCode::SriLanka => "LK",
            CountryCode::Sudan => "SD",
            CountryCode::Suriname => "SR",
            CountryCode::SvalbardAndJanMayen => "SJ",
            CountryCode::Sweden => "SE",
            CountryCode::Switzerland => "CH",
            CountryCode::SyrianArabRepublic => "SY",

            CountryCode::Taiwan => "TW",
            CountryCode::Tajikistan => "TJ",
            CountryCode::Tanzania => "TZ",
            CountryCode::Thailand => "TH",
            CountryCode::TimorLeste => "TL",
            CountryCode::Togo => "TG",
            CountryCode::Tokelau => "TK",
            CountryCode::Tonga => "TO",
            CountryCode::TrinidadAndTobago => "TT",
            CountryCode::Tunisia => "TN",
            CountryCode::Turkey => "TR",
            CountryCode::Turkmenistan => "TM",
            CountryCode::TurksAndCaicosIslands => "TC",
            CountryCode::Tuvalu => "TV",

            CountryCode::Uganda => "UG",
            CountryCode::Ukraine => "UA",
            CountryCode::UnitedArabEmirates => "AE",
            CountryCode::UnitedKingdom => "GB",
            CountryCode::UnitedStatesMinorOutlyingIslands => "UM",
            CountryCode::UnitedStates => "US",
            CountryCode::Uruguay => "UY",
            CountryCode::Uzbekistan => "UZ",

            CountryCode::Vanuatu => "VU",
            CountryCode::Venezuela => "VE",
            CountryCode::VietNam => "VN",
            CountryCode::VirginIslandsBritish => "VG",
            CountryCode::VirginIslandsUS => "VI",

            CountryCode::WallisAndFutuna => "WF",
            CountryCode::WesternSahara => "EH",

            CountryCode::Yemen => "YE",

            CountryCode::Zambia => "ZM",
            CountryCode::Zimbabwe => "ZW",

            CountryCode::Kosovo => "1A",
            CountryCode::UnitedKingdomNorthernIreland => "XI",
        }
    }
}

impl Serialize for CountryCode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}

#[cfg(test)]
mod tests {
    use crate::CountryCode;

    #[test]
    fn test_try_from() {
        let code = CountryCode::Ukraine;

        let string_repr = code.as_str().to_owned();
        let parsed_code = CountryCode::try_from(string_repr.as_str()).unwrap();
        debug_assert_eq!(parsed_code, code);
        panic!("wtf")
    }
}
