use serde::{Serialize, Serializer};

#[derive(Debug, Clone, Copy)]
pub enum CurrencyCode {
    UaeDirham,                                        // AED
    Afghani,                                          // AFN
    Lek,                                              // ALL
    ArmenianDram,                                     // AMD
    NetherlandsAntilleanGuilder,                      // ANG
    Kwanza,                                           // AOA
    ArgentinePeso,                                    // ARS
    AustralianDollar,                                 // AUD
    ArubanFlorin,                                     // AWG
    AzerbaijanManat,                                  // AZN
    ConvertibleMark,                                  // BAM
    BarbadosDollar,                                   // BBD
    Taka,                                             // BDT
    BulgarianLev,                                     // BGN
    BahrainiDinar,                                    // BHD
    BurundiFranc,                                     // BIF
    BermudianDollar,                                  // BMD
    BruneiDollar,                                     // BND
    Boliviano,                                        // BOB
    Mvdol,                                            // BOV
    BrazilianReal,                                    // BRL
    BahamianDollar,                                   // BSD
    Ngultrum,                                         // BTN
    Pula,                                             // BWP
    BelarusianRuble,                                  // BYN
    BelizeDollar,                                     // BZD
    CanadianDollar,                                   // CAD
    CongoleseFranc,                                   // CDF
    WirEuro,                                          // CHE
    SwissFranc,                                       // CHF
    WirFranc,                                         // CHW
    UnidadDeFomento,                                  // CLF
    ChileanPeso,                                      // CLP
    YuanRenminbi,                                     // CNY
    RenminbiOffshore,                                 // CNH (offshore)
    ColombianPeso,                                    // COP
    UnidadDeValorReal,                                // COU
    CostaRicanColon,                                  // CRC
    CubanPeso,                                        // CUP
    CaboVerdeEscudo,                                  // CVE
    CzechKoruna,                                      // CZK
    DjiboutiFranc,                                    // DJF
    DanishKrone,                                      // DKK
    DominicanPeso,                                    // DOP
    AlgerianDinar,                                    // DZD
    EgyptianPound,                                    // EGP
    Nakfa,                                            // ERN
    EthiopianBirr,                                    // ETB
    Euro,                                             // EUR
    FijiDollar,                                       // FJD
    FalklandIslandsPound,                             // FKP
    PoundSterling,                                    // GBP
    Lari,                                             // GEL
    GhanaCedi,                                        // GHS
    GibraltarPound,                                   // GIP
    Dalasi,                                           // GMD
    GuineanFranc,                                     // GNF
    Quetzal,                                          // GTQ
    GuyanaDollar,                                     // GYD
    HongKongDollar,                                   // HKD
    Lempira,                                          // HNL
    Gourde,                                           // HTG
    Forint,                                           // HUF
    Rupiah,                                           // IDR
    NewIsraeliSheqel,                                 // ILS
    IndianRupee,                                      // INR
    IraqiDinar,                                       // IQD
    IranianRial,                                      // IRR
    IcelandKrona,                                     // ISK
    JamaicanDollar,                                   // JMD
    JordanianDinar,                                   // JOD
    Yen,                                              // JPY
    KenyanShilling,                                   // KES
    Som,                                              // KGS
    Riel,                                             // KHR
    ComorianFranc,                                    // KMF
    NorthKoreanWon,                                   // KPW
    Won,                                              // KRW
    KuwaitiDinar,                                     // KWD
    CaymanIslandsDollar,                              // KYD
    Tenge,                                            // KZT
    LaoKip,                                           // LAK
    LebanesePound,                                    // LBP
    SriLankaRupee,                                    // LKR
    LiberianDollar,                                   // LRD
    Loti,                                             // LSL
    LibyanDinar,                                      // LYD
    MoroccanDirham,                                   // MAD
    MoldovanLeu,                                      // MDL
    MalagasyAriary,                                   // MGA
    Denar,                                            // MKD
    Kyat,                                             // MMK
    Tugrik,                                           // MNT
    Pataca,                                           // MOP
    Ouguiya,                                          // MRU
    MauritiusRupee,                                   // MUR
    Rufiyaa,                                          // MVR
    MalawiKwacha,                                     // MWK
    MexicanPeso,                                      // MXN
    MexicanUnidadDeInversion,                         // MXV
    MalaysianRinggit,                                 // MYR
    MozambiqueMetical,                                // MZN
    NamibiaDollar,                                    // NAD
    Naira,                                            // NGN
    CordobaOro,                                       // NIO
    NorwegianKrone,                                   // NOK
    NepaleseRupee,                                    // NPR
    NewZealandDollar,                                 // NZD
    RialOmani,                                        // OMR
    Balboa,                                           // PAB
    Sol,                                              // PEN
    Kina,                                             // PGK
    PhilippinePeso,                                   // PHP
    PakistanRupee,                                    // PKR
    Zloty,                                            // PLN
    Guarani,                                          // PYG
    QatariRial,                                       // QAR
    RomanianLeu,                                      // RON
    SerbianDinar,                                     // RSD
    RussianRuble,                                     // RUB
    RwandaFranc,                                      // RWF
    SaudiRiyal,                                       // SAR
    SolomonIslandsDollar,                             // SBD
    SeychellesRupee,                                  // SCR
    SudanesePound,                                    // SDG
    SwedishKrona,                                     // SEK
    SingaporeDollar,                                  // SGD
    SaintHelenaPound,                                 // SHP
    SierraLeone,                                      // SLE
    SomaliShilling,                                   // SOS
    SurinamDollar,                                    // SRD
    SouthSudanesePound,                               // SSP
    Dobra,                                            // STN
    ElSalvadorColon,                                  // SVC
    SyrianPound,                                      // SYP
    Lilangeni,                                        // SZL
    Baht,                                             // THB
    Somoni,                                           // TJS
    TurkmenistanNewManat,                             // TMT
    TunisianDinar,                                    // TND
    Paanga,                                           // TOP
    TurkishLira,                                      // TRY
    TrinidadAndTobagoDollar,                          // TTD
    NewTaiwanDollar,                                  // TWD
    TanzanianShilling,                                // TZS
    Hryvnia,                                          // UAH
    UgandaShilling,                                   // UGX
    UsDollar,                                         // USD
    UsDollarNextDay,                                  // USN
    UruguayPesoEnUnidadesIndexadas,                   // UYI
    PesoUruguayo,                                     // UYU
    UnidadPrevisional,                                // UYW
    UzbekistanSum,                                    // UZS
    BolivarSoberanoNewValuation,                      // VED
    BolivarSoberano,                                  // VES
    Dong,                                             // VND
    Vatu,                                             // VUV
    Tala,                                             // WST
    CfaFrancBeac,                                     // XAF
    Silver,                                           // XAG
    Gold,                                             // XAU
    BondMarketsUnitEuropeanCompositeUnit,             // XBA
    BondMarketsUnitEuropeanMonetaryUnit,              // XBB
    BondMarketsUnitEuropeanUnitOfAccount9,            // XBC
    BondMarketsUnitEuropeanUnitOfAccount17,           // XBD
    EastCaribbeanDollar,                              // XCD
    Sdr,                                              // XDR
    CfaFrancBceao,                                    // XOF
    Palladium,                                        // XPD
    CfpFranc,                                         // XPF
    Platinum,                                         // XPT
    Sucre,                                            // XSU
    TestingPurposes,                                  // XTS
    AdbUnitOfAccount,                                 // XUA
    NoCurrency,                                       // XXX
    YemeniRial,                                       // YER
    Rand,                                             // ZAR
    ZambianKwacha,                                    // ZMW
    ZimbabweGold,                                     // ZWG
}

impl CurrencyCode {
    pub fn as_str(&self) -> &str {
        match self {
            CurrencyCode::UaeDirham => "AED",
            CurrencyCode::Afghani => "AFN",
            CurrencyCode::Lek => "ALL",
            CurrencyCode::ArmenianDram => "AMD",
            CurrencyCode::NetherlandsAntilleanGuilder => "ANG",
            CurrencyCode::Kwanza => "AOA",
            CurrencyCode::ArgentinePeso => "ARS",
            CurrencyCode::AustralianDollar => "AUD",
            CurrencyCode::ArubanFlorin => "AWG",
            CurrencyCode::AzerbaijanManat => "AZN",
            CurrencyCode::ConvertibleMark => "BAM",
            CurrencyCode::BarbadosDollar => "BBD",
            CurrencyCode::Taka => "BDT",
            CurrencyCode::BulgarianLev => "BGN",
            CurrencyCode::BahrainiDinar => "BHD",
            CurrencyCode::BurundiFranc => "BIF",
            CurrencyCode::BermudianDollar => "BMD",
            CurrencyCode::BruneiDollar => "BND",
            CurrencyCode::Boliviano => "BOB",
            CurrencyCode::Mvdol => "BOV",
            CurrencyCode::BrazilianReal => "BRL",
            CurrencyCode::BahamianDollar => "BSD",
            CurrencyCode::Ngultrum => "BTN",
            CurrencyCode::Pula => "BWP",
            CurrencyCode::BelarusianRuble => "BYN",
            CurrencyCode::BelizeDollar => "BZD",
            CurrencyCode::CanadianDollar => "CAD",
            CurrencyCode::CongoleseFranc => "CDF",
            CurrencyCode::WirEuro => "CHE",
            CurrencyCode::SwissFranc => "CHF",
            CurrencyCode::WirFranc => "CHW",
            CurrencyCode::UnidadDeFomento => "CLF",
            CurrencyCode::ChileanPeso => "CLP",
            CurrencyCode::YuanRenminbi => "CNY",
            CurrencyCode::RenminbiOffshore => "CNH",
            CurrencyCode::ColombianPeso => "COP",
            CurrencyCode::UnidadDeValorReal => "COU",
            CurrencyCode::CostaRicanColon => "CRC",
            CurrencyCode::CubanPeso => "CUP",
            CurrencyCode::CaboVerdeEscudo => "CVE",
            CurrencyCode::CzechKoruna => "CZK",
            CurrencyCode::DjiboutiFranc => "DJF",
            CurrencyCode::DanishKrone => "DKK",
            CurrencyCode::DominicanPeso => "DOP",
            CurrencyCode::AlgerianDinar => "DZD",
            CurrencyCode::EgyptianPound => "EGP",
            CurrencyCode::Nakfa => "ERN",
            CurrencyCode::EthiopianBirr => "ETB",
            CurrencyCode::Euro => "EUR",
            CurrencyCode::FijiDollar => "FJD",
            CurrencyCode::FalklandIslandsPound => "FKP",
            CurrencyCode::PoundSterling => "GBP",
            CurrencyCode::Lari => "GEL",
            CurrencyCode::GhanaCedi => "GHS",
            CurrencyCode::GibraltarPound => "GIP",
            CurrencyCode::Dalasi => "GMD",
            CurrencyCode::GuineanFranc => "GNF",
            CurrencyCode::Quetzal => "GTQ",
            CurrencyCode::GuyanaDollar => "GYD",
            CurrencyCode::HongKongDollar => "HKD",
            CurrencyCode::Lempira => "HNL",
            CurrencyCode::Gourde => "HTG",
            CurrencyCode::Forint => "HUF",
            CurrencyCode::Rupiah => "IDR",
            CurrencyCode::NewIsraeliSheqel => "ILS",
            CurrencyCode::IndianRupee => "INR",
            CurrencyCode::IraqiDinar => "IQD",
            CurrencyCode::IranianRial => "IRR",
            CurrencyCode::IcelandKrona => "ISK",
            CurrencyCode::JamaicanDollar => "JMD",
            CurrencyCode::JordanianDinar => "JOD",
            CurrencyCode::Yen => "JPY",
            CurrencyCode::KenyanShilling => "KES",
            CurrencyCode::Som => "KGS",
            CurrencyCode::Riel => "KHR",
            CurrencyCode::ComorianFranc => "KMF",
            CurrencyCode::NorthKoreanWon => "KPW",
            CurrencyCode::Won => "KRW",
            CurrencyCode::KuwaitiDinar => "KWD",
            CurrencyCode::CaymanIslandsDollar => "KYD",
            CurrencyCode::Tenge => "KZT",
            CurrencyCode::LaoKip => "LAK",
            CurrencyCode::LebanesePound => "LBP",
            CurrencyCode::SriLankaRupee => "LKR",
            CurrencyCode::LiberianDollar => "LRD",
            CurrencyCode::Loti => "LSL",
            CurrencyCode::LibyanDinar => "LYD",
            CurrencyCode::MoroccanDirham => "MAD",
            CurrencyCode::MoldovanLeu => "MDL",
            CurrencyCode::MalagasyAriary => "MGA",
            CurrencyCode::Denar => "MKD",
            CurrencyCode::Kyat => "MMK",
            CurrencyCode::Tugrik => "MNT",
            CurrencyCode::Pataca => "MOP",
            CurrencyCode::Ouguiya => "MRU",
            CurrencyCode::MauritiusRupee => "MUR",
            CurrencyCode::Rufiyaa => "MVR",
            CurrencyCode::MalawiKwacha => "MWK",
            CurrencyCode::MexicanPeso => "MXN",
            CurrencyCode::MexicanUnidadDeInversion => "MXV",
            CurrencyCode::MalaysianRinggit => "MYR",
            CurrencyCode::MozambiqueMetical => "MZN",
            CurrencyCode::NamibiaDollar => "NAD",
            CurrencyCode::Naira => "NGN",
            CurrencyCode::CordobaOro => "NIO",
            CurrencyCode::NorwegianKrone => "NOK",
            CurrencyCode::NepaleseRupee => "NPR",
            CurrencyCode::NewZealandDollar => "NZD",
            CurrencyCode::RialOmani => "OMR",
            CurrencyCode::Balboa => "PAB",
            CurrencyCode::Sol => "PEN",
            CurrencyCode::Kina => "PGK",
            CurrencyCode::PhilippinePeso => "PHP",
            CurrencyCode::PakistanRupee => "PKR",
            CurrencyCode::Zloty => "PLN",
            CurrencyCode::Guarani => "PYG",
            CurrencyCode::QatariRial => "QAR",
            CurrencyCode::RomanianLeu => "RON",
            CurrencyCode::SerbianDinar => "RSD",
            CurrencyCode::RussianRuble => "RUB",
            CurrencyCode::RwandaFranc => "RWF",
            CurrencyCode::SaudiRiyal => "SAR",
            CurrencyCode::SolomonIslandsDollar => "SBD",
            CurrencyCode::SeychellesRupee => "SCR",
            CurrencyCode::SudanesePound => "SDG",
            CurrencyCode::SwedishKrona => "SEK",
            CurrencyCode::SingaporeDollar => "SGD",
            CurrencyCode::SaintHelenaPound => "SHP",
            CurrencyCode::SierraLeone => "SLE",
            CurrencyCode::SomaliShilling => "SOS",
            CurrencyCode::SurinamDollar => "SRD",
            CurrencyCode::SouthSudanesePound => "SSP",
            CurrencyCode::Dobra => "STN",
            CurrencyCode::ElSalvadorColon => "SVC",
            CurrencyCode::SyrianPound => "SYP",
            CurrencyCode::Lilangeni => "SZL",
            CurrencyCode::Baht => "THB",
            CurrencyCode::Somoni => "TJS",
            CurrencyCode::TurkmenistanNewManat => "TMT",
            CurrencyCode::TunisianDinar => "TND",
            CurrencyCode::Paanga => "TOP",
            CurrencyCode::TurkishLira => "TRY",
            CurrencyCode::TrinidadAndTobagoDollar => "TTD",
            CurrencyCode::NewTaiwanDollar => "TWD",
            CurrencyCode::TanzanianShilling => "TZS",
            CurrencyCode::Hryvnia => "UAH",
            CurrencyCode::UgandaShilling => "UGX",
            CurrencyCode::UsDollar => "USD",
            CurrencyCode::UsDollarNextDay => "USN",
            CurrencyCode::UruguayPesoEnUnidadesIndexadas => "UYI",
            CurrencyCode::PesoUruguayo => "UYU",
            CurrencyCode::UnidadPrevisional => "UYW",
            CurrencyCode::UzbekistanSum => "UZS",
            CurrencyCode::BolivarSoberanoNewValuation => "VED",
            CurrencyCode::BolivarSoberano => "VES",
            CurrencyCode::Dong => "VND",
            CurrencyCode::Vatu => "VUV",
            CurrencyCode::Tala => "WST",
            CurrencyCode::CfaFrancBeac => "XAF",
            CurrencyCode::Silver => "XAG",
            CurrencyCode::Gold => "XAU",
            CurrencyCode::BondMarketsUnitEuropeanCompositeUnit => "XBA",
            CurrencyCode::BondMarketsUnitEuropeanMonetaryUnit => "XBB",
            CurrencyCode::BondMarketsUnitEuropeanUnitOfAccount9 => "XBC",
            CurrencyCode::BondMarketsUnitEuropeanUnitOfAccount17 => "XBD",
            CurrencyCode::EastCaribbeanDollar => "XCD",
            CurrencyCode::Sdr => "XDR",
            CurrencyCode::CfaFrancBceao => "XOF",
            CurrencyCode::Palladium => "XPD",
            CurrencyCode::CfpFranc => "XPF",
            CurrencyCode::Platinum => "XPT",
            CurrencyCode::Sucre => "XSU",
            CurrencyCode::TestingPurposes => "XTS",
            CurrencyCode::AdbUnitOfAccount => "XUA",
            CurrencyCode::NoCurrency => "XXX",
            CurrencyCode::YemeniRial => "YER",
            CurrencyCode::Rand => "ZAR",
            CurrencyCode::ZambianKwacha => "ZMW",
            CurrencyCode::ZimbabweGold => "ZWG",
        }
    }
}

impl Serialize for CurrencyCode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}
