use serde::{Serialize,Serializer};

#[derive(Debug,Clone,Copy)]
#[allow(non_camel_case_types)]
pub enum IdentifierSchemeCode {
    GTIN,
    SIRENE,
    BelgiumFinancial,
    NBS_OSI,
    USA_FED_GOV_OSI,
    USA_DOD_OSI,
    Organisationsnummer,
    LE_NUMERO_NATIONAL,
    SIRET_CODE,
    ISO_9541_Part2,
    Amateur_Radio_Organizations,
    ECMA,
    VSA_FTP_CODE,
    NIST_OSI,
    EDI,
    EWOS,
    COMMON_LANGUAGE,
    SNA_OSI,
    Air_Transport_Industry,
    CERN,
    SWIFT,
    OSF_Distributed_Computing,
    NORDUnet,
    DEC,
    OSI_ASIA_OCEANIA,
    NATO_ISO_6523,
    ATN,
    ISO_6523,
    All_Union_Classifier,
    ATT_OSI,
    EDI_Partner,
    Telecom_Australia,
    SGW_OSI,
    Reuter_Open_Address,
    ISO_6523_ICD,
    TeleTrust,
    LY_tunnus,
    Australian_GOSIP,
    OZ_DOD_OSI,
    Unilever,
    Citicorp,
    DBP_Telekom,
    HydroNETT,
    TISI,
    ICI,
    FUNLOC,
    BULL_ODI_DSA_UNIX,
    OSINZ,
    Auckland_Area_Health,
    Firmenich,
    AGFA_DIS,
    SMPTE,
    Migros_Network,
    ISO6523_ICDPCR,
    Energy_Net,
    Nokia,
    Saint_Gobain,
    Siemens_Corporate,
    DANZNET,
    DUNS_Number,
    SOFFEX_OSI,
    KPN_OVN,
    ascomOSINet,
    UTC,
    SOLVAY_OSI,
    Roche_Corporate,
    ZellwegerOSINet,
    Intel_Corporation,
    SITA,
    DaimlerChrysler,
    LEGO_OSI,
    NAVISTAR_OSI,
    ICD_Formatted_ATM,
    ARINC,
    Alcanet_Alcatel_Alsthom,
    UNINFO_Italian_Identification,
    UNINFO_Italian_Addressing,
    Mitel,
    ATM_Forum,
    UK_NHS,
    International_NSAP,
    Norwegian_Telecommunications,
    Advanced_Telecommunications,
    Athens_Chamber,
    Swiss_Chambers,
    USCIB,
    Belgian_Chambers,
    EAN_Location_Code,
    British_Chambers,
    Internet_IP_Addressing,
    Cisco_Systems,
    Revenue_Canada,
    DIHT,
    Hewlett_Packard,
    Danish_Chamber,
    Ediforum_Italia,
    Tel_Aviv_Jaffa,
    Siemens_Supervisory,
    PNG_ICD,
    South_African_Code,
    HEAG,
    BT_ICD,
    Portuguese_Chamber,
    Dutch_Chambers,
    Swedish_Chambers,
    Australian_Chambers,
    BellSouth_ICD,
    Bell_Atlantic,
    Object_Identifiers,
    ISO_Standards_Organizations,
    OriginNet,
    Check_Point,
    Pacific_Bell,
    PSS_Object_Identifiers,
    STENTOR_ICD,
    ATM_Network_ZN96,
    MCI_OSI,
    Advantis,
    Affable_Software,
    BB_DATA,
    BASF,
    IOTA,
    Henkel,
    GTE_OSI,
    Dresdner_Bank,
    BCNR,
    BPI,
    European_Commission,
    National_Organizations,
    Certicom,
    TC68_OID,
    Infonet_Services,
    SIA_Object_Identifiers,
    Cable_Wireless,
    Global_AESA,
    France_Telecom,
    Savvis_Communications,
    Toshiba_TOPAS,
    NATO_CAGE,
    SECETI,
    EINESTEINet,
    DoDAAC,
    DGCP,
    DGI,
    Standard_Company_Code,
    ITU_DNIC,
    Global_Business_Identifier,
    Madge_Networks,
    Australian_Business_Number,
    Edira_Scheme,
    Concert_Global_Network,
    ICO,
    Global_Crossing_AESA,
    AUNA,
    Dutch_KPN_Telecom,
    ICO_Act,
    ACTALIS,
    ECCMA,
    CEN_ISSS,
    US_EPA,
    TELUS,
    FIEIE,
    Swissguide,
    Priority_Telecom,
    Vodafone_Ireland,
    Swiss_Federal_Business,
    Teikoku,
    Luxembourg_CP_CPS,
    PROLIST,
    eCI_ass,
    StepNexus,
    Siemens_AG,
    Paradine,
    Odette_International,
    Route1_MobiNET,
    Penango,
    Lithuanian_military_PKI,
    Swiss_Unique_Business,
    DIGSTORG,
    Perceval,
    TrustPoint,
    Amazon,
    Corporate_Number,
    European_Business_Identifier,
    OIN,
    Estonia_Company_Code,
    Organisasjonsnummer,
    UBL_BE,
    KOIOS,
    Singapore_E_Invoice,
    Icelandic_identifier,
    APPLiA,
    ERSTORG,
    LEI,
    Lithuania_Legal_Entity,
    Codice_Univoco,
    Indirizzo_di_Posta,
    eDelivery_Network,
    Leitweg_ID,
    CODDEST,
    RCI,
    PiLog,
    Numero_d_entreprise,
    GS1_identification_keys,
    CODICE_FISCALE,
    PARTITA_IVA,
    Finnish_Organization_Identifier,
    Finnish_Organization_VAT,
}

impl IdentifierSchemeCode {
    pub fn as_str(&self) -> &str {
        match self {
            IdentifierSchemeCode::GTIN => "0160",
            IdentifierSchemeCode::SIRENE => "0002",
            IdentifierSchemeCode::BelgiumFinancial => "0003",
            IdentifierSchemeCode::NBS_OSI => "0004",
            IdentifierSchemeCode::USA_FED_GOV_OSI => "0005",
            IdentifierSchemeCode::USA_DOD_OSI => "0006",
            IdentifierSchemeCode::Organisationsnummer => "0007",
            IdentifierSchemeCode::LE_NUMERO_NATIONAL => "0008",
            IdentifierSchemeCode::SIRET_CODE => "0009",
            IdentifierSchemeCode::ISO_9541_Part2 => "0010",
            IdentifierSchemeCode::Amateur_Radio_Organizations => "0011",
            IdentifierSchemeCode::ECMA => "0012",
            IdentifierSchemeCode::VSA_FTP_CODE => "0013",
            IdentifierSchemeCode::NIST_OSI => "0014",
            IdentifierSchemeCode::EDI => "0015",
            IdentifierSchemeCode::EWOS => "0016",
            IdentifierSchemeCode::COMMON_LANGUAGE => "0017",
            IdentifierSchemeCode::SNA_OSI => "0018",
            IdentifierSchemeCode::Air_Transport_Industry => "0019",
            IdentifierSchemeCode::CERN => "0020",
            IdentifierSchemeCode::SWIFT => "0021",
            IdentifierSchemeCode::OSF_Distributed_Computing => "0022",
            IdentifierSchemeCode::NORDUnet => "0023",
            IdentifierSchemeCode::DEC => "0024",
            IdentifierSchemeCode::OSI_ASIA_OCEANIA => "0025",
            IdentifierSchemeCode::NATO_ISO_6523 => "0026",
            IdentifierSchemeCode::ATN => "0027",
            IdentifierSchemeCode::ISO_6523 => "0028",
            IdentifierSchemeCode::All_Union_Classifier => "0029",
            IdentifierSchemeCode::ATT_OSI => "0030",
            IdentifierSchemeCode::EDI_Partner => "0031",
            IdentifierSchemeCode::Telecom_Australia => "0032",
            IdentifierSchemeCode::SGW_OSI => "0033",
            IdentifierSchemeCode::Reuter_Open_Address => "0034",
            IdentifierSchemeCode::ISO_6523_ICD => "0035",
            IdentifierSchemeCode::TeleTrust => "0036",
            IdentifierSchemeCode::LY_tunnus => "0037",
            IdentifierSchemeCode::Australian_GOSIP => "0038",
            IdentifierSchemeCode::OZ_DOD_OSI => "0039",
            IdentifierSchemeCode::Unilever => "0040",
            IdentifierSchemeCode::Citicorp => "0041",
            IdentifierSchemeCode::DBP_Telekom => "0042",
            IdentifierSchemeCode::HydroNETT => "0043",
            IdentifierSchemeCode::TISI => "0044",
            IdentifierSchemeCode::ICI => "0045",
            IdentifierSchemeCode::FUNLOC => "0046",
            IdentifierSchemeCode::BULL_ODI_DSA_UNIX => "0047",
            IdentifierSchemeCode::OSINZ => "0048",
            IdentifierSchemeCode::Auckland_Area_Health => "0049",
            IdentifierSchemeCode::Firmenich => "0050",
            IdentifierSchemeCode::AGFA_DIS => "0051",
            IdentifierSchemeCode::SMPTE => "0052",
            IdentifierSchemeCode::Migros_Network => "0053",
            IdentifierSchemeCode::ISO6523_ICDPCR => "0054",
            IdentifierSchemeCode::Energy_Net => "0055",
            IdentifierSchemeCode::Nokia => "0056",
            IdentifierSchemeCode::Saint_Gobain => "0057",
            IdentifierSchemeCode::Siemens_Corporate => "0058",
            IdentifierSchemeCode::DANZNET => "0059",
            IdentifierSchemeCode::DUNS_Number => "0060",
            IdentifierSchemeCode::SOFFEX_OSI => "0061",
            IdentifierSchemeCode::KPN_OVN => "0062",
            IdentifierSchemeCode::ascomOSINet => "0063",
            IdentifierSchemeCode::UTC => "0064",
            IdentifierSchemeCode::SOLVAY_OSI => "0065",
            IdentifierSchemeCode::Roche_Corporate => "0066",
            IdentifierSchemeCode::ZellwegerOSINet => "0067",
            IdentifierSchemeCode::Intel_Corporation => "0068",
            IdentifierSchemeCode::SITA => "0069",
            IdentifierSchemeCode::DaimlerChrysler => "0070",
            IdentifierSchemeCode::LEGO_OSI => "0071",
            IdentifierSchemeCode::NAVISTAR_OSI => "0072",
            IdentifierSchemeCode::ICD_Formatted_ATM => "0073",
            IdentifierSchemeCode::ARINC => "0074",
            IdentifierSchemeCode::Alcanet_Alcatel_Alsthom => "0075",
            IdentifierSchemeCode::UNINFO_Italian_Identification => "0076",
            IdentifierSchemeCode::UNINFO_Italian_Addressing => "0077",
            IdentifierSchemeCode::Mitel => "0078",
            IdentifierSchemeCode::ATM_Forum => "0079",
            IdentifierSchemeCode::UK_NHS => "0080",
            IdentifierSchemeCode::International_NSAP => "0081",
            IdentifierSchemeCode::Norwegian_Telecommunications => "0082",
            IdentifierSchemeCode::Advanced_Telecommunications => "0083",
            IdentifierSchemeCode::Athens_Chamber => "0084",
            IdentifierSchemeCode::Swiss_Chambers => "0085",
            IdentifierSchemeCode::USCIB => "0086",
            IdentifierSchemeCode::Belgian_Chambers => "0087",
            IdentifierSchemeCode::EAN_Location_Code => "0088",
            IdentifierSchemeCode::British_Chambers => "0089",
            IdentifierSchemeCode::Internet_IP_Addressing => "0090",
            IdentifierSchemeCode::Cisco_Systems => "0091",
            IdentifierSchemeCode::Revenue_Canada => "0093",
            IdentifierSchemeCode::DIHT => "0094",
            IdentifierSchemeCode::Hewlett_Packard => "0095",
            IdentifierSchemeCode::Danish_Chamber => "0096",
            IdentifierSchemeCode::Ediforum_Italia => "0097",
            IdentifierSchemeCode::Tel_Aviv_Jaffa => "0098",
            IdentifierSchemeCode::Siemens_Supervisory => "0099",
            IdentifierSchemeCode::PNG_ICD => "0100",
            IdentifierSchemeCode::South_African_Code => "0101",
            IdentifierSchemeCode::HEAG => "0102",
            IdentifierSchemeCode::BT_ICD => "0104",
            IdentifierSchemeCode::Portuguese_Chamber => "0105",
            IdentifierSchemeCode::Dutch_Chambers => "0106",
            IdentifierSchemeCode::Swedish_Chambers => "0107",
            IdentifierSchemeCode::Australian_Chambers => "0108",
            IdentifierSchemeCode::BellSouth_ICD => "0109",
            IdentifierSchemeCode::Bell_Atlantic => "0110",
            IdentifierSchemeCode::Object_Identifiers => "0111",
            IdentifierSchemeCode::ISO_Standards_Organizations => "0112",
            IdentifierSchemeCode::OriginNet => "0113",
            IdentifierSchemeCode::Check_Point => "0114",
            IdentifierSchemeCode::Pacific_Bell => "0115",
            IdentifierSchemeCode::PSS_Object_Identifiers => "0116",
            IdentifierSchemeCode::STENTOR_ICD => "0117",
            IdentifierSchemeCode::ATM_Network_ZN96 => "0118",
            IdentifierSchemeCode::MCI_OSI => "0119",
            IdentifierSchemeCode::Advantis => "0120",
            IdentifierSchemeCode::Affable_Software => "0121",
            IdentifierSchemeCode::BB_DATA => "0122",
            IdentifierSchemeCode::BASF => "0123",
            IdentifierSchemeCode::IOTA => "0124",
            IdentifierSchemeCode::Henkel => "0125",
            IdentifierSchemeCode::GTE_OSI => "0126",
            IdentifierSchemeCode::Dresdner_Bank => "0127",
            IdentifierSchemeCode::BCNR => "0128",
            IdentifierSchemeCode::BPI => "0129",
            IdentifierSchemeCode::European_Commission => "0130",
            IdentifierSchemeCode::National_Organizations => "0131",
            IdentifierSchemeCode::Certicom => "0132",
            IdentifierSchemeCode::TC68_OID => "0133",
            IdentifierSchemeCode::Infonet_Services => "0134",
            IdentifierSchemeCode::SIA_Object_Identifiers => "0135",
            IdentifierSchemeCode::Cable_Wireless => "0136",
            IdentifierSchemeCode::Global_AESA => "0137",
            IdentifierSchemeCode::France_Telecom => "0138",
            IdentifierSchemeCode::Savvis_Communications => "0139",
            IdentifierSchemeCode::Toshiba_TOPAS => "0140",
            IdentifierSchemeCode::NATO_CAGE => "0141",
            IdentifierSchemeCode::SECETI => "0142",
            IdentifierSchemeCode::EINESTEINet => "0143",
            IdentifierSchemeCode::DoDAAC => "0144",
            IdentifierSchemeCode::DGCP => "0145",
            IdentifierSchemeCode::DGI => "0146",
            IdentifierSchemeCode::Standard_Company_Code => "0147",
            IdentifierSchemeCode::ITU_DNIC => "0148",
            IdentifierSchemeCode::Global_Business_Identifier => "0149",
            IdentifierSchemeCode::Madge_Networks => "0150",
            IdentifierSchemeCode::Australian_Business_Number => "0151",
            IdentifierSchemeCode::Edira_Scheme => "0152",
            IdentifierSchemeCode::Concert_Global_Network => "0153",
            IdentifierSchemeCode::ICO => "0154",
            IdentifierSchemeCode::Global_Crossing_AESA => "0155",
            IdentifierSchemeCode::AUNA => "0156",
            IdentifierSchemeCode::Dutch_KPN_Telecom => "0157",
            IdentifierSchemeCode::ICO_Act => "0158",
            IdentifierSchemeCode::ACTALIS => "0159",
            IdentifierSchemeCode::ECCMA => "0161",
            IdentifierSchemeCode::CEN_ISSS => "0162",
            IdentifierSchemeCode::US_EPA => "0163",
            IdentifierSchemeCode::TELUS => "0164",
            IdentifierSchemeCode::FIEIE => "0165",
            IdentifierSchemeCode::Swissguide => "0166",
            IdentifierSchemeCode::Priority_Telecom => "0167",
            IdentifierSchemeCode::Vodafone_Ireland => "0168",
            IdentifierSchemeCode::Swiss_Federal_Business => "0169",
            IdentifierSchemeCode::Teikoku => "0170",
            IdentifierSchemeCode::Luxembourg_CP_CPS => "0171",
            IdentifierSchemeCode::PROLIST => "0172",
            IdentifierSchemeCode::eCI_ass => "0173",
            IdentifierSchemeCode::StepNexus => "0174",
            IdentifierSchemeCode::Siemens_AG => "0175",
            IdentifierSchemeCode::Paradine => "0176",
            IdentifierSchemeCode::Odette_International => "0177",
            IdentifierSchemeCode::Route1_MobiNET => "0178",
            IdentifierSchemeCode::Penango => "0179",
            IdentifierSchemeCode::Lithuanian_military_PKI => "0180",
            IdentifierSchemeCode::Swiss_Unique_Business => "0183",
            IdentifierSchemeCode::DIGSTORG => "0184",
            IdentifierSchemeCode::Perceval => "0185",
            IdentifierSchemeCode::TrustPoint => "0186",
            IdentifierSchemeCode::Amazon => "0187",
            IdentifierSchemeCode::Corporate_Number => "0188",
            IdentifierSchemeCode::European_Business_Identifier => "0189",
            IdentifierSchemeCode::OIN => "0190",
            IdentifierSchemeCode::Estonia_Company_Code => "0191",
            IdentifierSchemeCode::Organisasjonsnummer => "0192",
            IdentifierSchemeCode::UBL_BE => "0193",
            IdentifierSchemeCode::KOIOS => "0194",
            IdentifierSchemeCode::Singapore_E_Invoice => "0195",
            IdentifierSchemeCode::Icelandic_identifier => "0196",
            IdentifierSchemeCode::APPLiA => "0197",
            IdentifierSchemeCode::ERSTORG => "0198",
            IdentifierSchemeCode::LEI => "0199",
            IdentifierSchemeCode::Lithuania_Legal_Entity => "0200",
            IdentifierSchemeCode::Codice_Univoco => "0201",
            IdentifierSchemeCode::Indirizzo_di_Posta => "0202",
            IdentifierSchemeCode::eDelivery_Network => "0203",
            IdentifierSchemeCode::Leitweg_ID => "0204",
            IdentifierSchemeCode::CODDEST => "0205",
            IdentifierSchemeCode::RCI => "0206",
            IdentifierSchemeCode::PiLog => "0207",
            IdentifierSchemeCode::Numero_d_entreprise => "0208",
            IdentifierSchemeCode::GS1_identification_keys => "0209",
            IdentifierSchemeCode::CODICE_FISCALE => "0210",
            IdentifierSchemeCode::PARTITA_IVA => "0211",
            IdentifierSchemeCode::Finnish_Organization_Identifier => "0212",
            IdentifierSchemeCode::Finnish_Organization_VAT => "0213",
        }
    }
}

impl Serialize for IdentifierSchemeCode {
    fn serialize<S>(&self, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(self.as_str())
    }
}